# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Farantos Dimitris
# Description of the Site
description: Economist & Data Scientist
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://wallpaper.forfun.com/fetch/49/499182e9a3a53124c4230aeb1014c03d.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: dimfrd@hotmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: dimitrios-farantos
github_username:  dimfrd
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: DimFrd

# Name of the Author
author-name: Dimitris Farantos
# URL for the Image of the Author
author-image: assets/images/testme.png
# 60 Words About the Author
author-about: I am a dedicated economist with a background in accounting and a strong focus on analysis. Recently, I completed an intensive bootcamp to enhance my analytical skills, aiming to extract meaningful insights from complex data. I am well-organized, adaptable, and capable of working effectively both within a team or independently as needed. My goal is to apply my expertise to deliver critical insights and support strategic business objectives.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/dimfrd

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
